"""private messages

Revision ID: 05f645438281
Revises: 29796ad81f8e
Create Date: 2020-11-04 12:50:44.816435

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '05f645438281'
down_revision = '29796ad81f8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_message_read_time', sa.DateTime(), nullable=True))
    op.drop_column('user', 'las_message_read_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('las_message_read_time', mysql.DATETIME(), nullable=True))
    op.drop_column('user', 'last_message_read_time')
    # ### end Alembic commands ###
